labelled_output <- function(label){
  function(x, ...){
    cat(paste0(label, "\n"))
    cat(x[[1]], "\n")
  }
}

print.alpha <- labelled_output("Kuder Richardson's coefficient alpha (tau-equivalent reliability)")
print.mu2 <- labelled_output("Ten Berge and Zegers' mu2")
print.mu3 <- labelled_output("Ten Berge and Zegers' mu3")
print.mu4 <- labelled_output("Ten Berge and Zegers' mu4")
print.feldt <- labelled_output("Feldt's classical congeneric reliability")
print.gilmer <- labelled_output("Gilmer-Feldt's reliability coefficient")
print.joreskog <- labelled_output("Joreskog's congeneric (unidimensional CFA) coefficient")
print.hancock <- labelled_output("Hancock's H (CFA maximal reliability)")
print.heise <- labelled_output("Heise-Borhnstedt's Omega")
print.kaisercaffrey <- labelled_output("Kaiser-Caffrey's alpha")
print.unirel <- function(x, ...){
  cat("18 unidimensional reliability coefficients")
  cat("\ncoefficient alpha (tau-equivalent reliability, mu0)               ")
  cat(x$alpha)
  cat("\nstandardized alpha                                                ")
  cat(x$std_alpha)
  cat("\nGuttman's lambda2 (mu1)                                           ")
  cat(x$lambda2)
  cat("\nTen Berge and Zegers' mu2                                         ")
  cat(x$mu2)
  cat("\nTen Berge and Zegers' mu3                                         ")
  cat(x$mu3)
  cat("\nTen Berge and Zegers' mu4                                         ")
  cat(x$mu4)
  cat("\nFeldt's classical congeneric reliability                          ")
  cat(x$feldt)
  cat("\nGilmer-Feldt's reliability coefficient                            ")
  cat(x$gilmer)
  cat("\nJoreskog's congeneric (unidimensional CFA) coefficient            ")
  cat(x$joreskog)
  cat("\nHancock's H (CFA version of maximal reliability)                  ")
  cat(x$hancock)
  cat("\nHeise-Borhnstedt's Omega                                          ")
  cat(x$heise)
  cat("\nKaiser-Caffrey's alpha (principal component analysis reliability) ")
  cat(x$kaisercaffrey)
  cat("\nGuttman's lambda5                                                 ")
  cat(x$lambda5)
  cat("\nGuttman's lambda6                                                 ")
  cat(x$lambda6)
  cat("\nMaximum among Guttman's lambda2, lambda5, and lambda6             ")
  cat(x$max_lambda)
  cat("\nMaximum among all possible split-half reliability(lambda4)        ")
  cat(x$lambda4_max)
  cat("\n75th percentile among all possible split-half reliability(lambda4)")
  cat(x$lambda4_75)
  cat("\nGLB.algebraic (greatest lower bounds by Moltner & Revelle (2015)) ")
  cat(x$glb.algebraic)
  cat("\nGLB.fa (greatest lower bounds by Ten Berge & Kiers (1991))        ")
  cat(x$glb.fa)
}

