DIGITS <- 6
labelled_output <- function(label){
  function(x, ...){
    cat(paste0(label, "\n"))
    cat(round(x[[1]], DIGITS), "\n")
  }
}

print.alpha <- labelled_output("Kuder Richardson's coefficient alpha (tau-equivalent reliability)")
print.mu2 <- labelled_output("Ten Berge and Zegers' mu2")
print.mu3 <- labelled_output("Ten Berge and Zegers' mu3")
print.mu4 <- labelled_output("Ten Berge and Zegers' mu4")
print.feldt <- labelled_output("Feldt's classical congeneric reliability")
print.gilmer <- labelled_output("Gilmer-Feldt's reliability coefficient")
print.joreskog <- labelled_output("Joreskog's congeneric (unidimensional CFA) coefficient")
print.hancock <- labelled_output("Hancock's H (CFA maximal reliability)")
print.heise <- labelled_output("Heise-Borhnstedt's Omega")
print.kaisercaffrey <- labelled_output("Kaiser-Caffrey's alpha")
print.unirel <- function(x, ...){
  cat("18 unidimensional reliability coefficients")
  cat("\ncoefficient alpha (tau-equivalent reliability, mu0)               ")
  cat(round(x$alpha, DIGITS))
  cat("\nGuttman's lambda2 (mu1)                                           ")
  cat(round(x$lambda2, DIGITS))
  cat("\nTen Berge and Zegers' mu2                                         ")
  cat(round(x$mu2, DIGITS))
  cat("\nTen Berge and Zegers' mu3                                         ")
  cat(round(x$mu3, DIGITS))
  cat("\nTen Berge and Zegers' mu4                                         ")
  cat(round(x$mu4, DIGITS))
  cat("\nFeldt's classical congeneric reliability                          ")
  cat(round(x$feldt, DIGITS))
  cat("\nGilmer-Feldt's reliability coefficient                            ")
  cat(round(x$gilmer, DIGITS))
  cat("\nJoreskog's congeneric (unidimensional CFA) coefficient            ")
  cat(round(x$joreskog, DIGITS))
  cat("\nHancock's H (CFA version of maximal reliability)                  ")
  cat(round(x$hancock, DIGITS))
  cat("\nHeise-Borhnstedt's Omega                                          ")
  cat(round(x$heise, DIGITS))
  cat("\nKaiser-Caffrey's alpha (principal component analysis reliability) ")
  cat(round(x$kaisercaffrey, DIGITS))
  cat("\nGuttman's lambda5                                                 ")
  cat(round(x$lambda5, DIGITS))
  cat("\nGuttman's lambda6                                                 ")
  cat(round(x$lambda6, DIGITS))
  cat("\nMaximum among Guttman's lambda2, lambda5, and lambda6             ")
  cat(round(x$max_lambda, DIGITS))
  cat("\nMaximum among all possible split-half reliability(lambda4)        ")
  cat(round(x$lambda4_max, DIGITS))
  cat("\n75th percentile among all possible split-half reliability(lambda4)")
  cat(round(x$lambda4_75, DIGITS))
  cat("\nGLB.algebraic (greatest lower bounds by Moltner & Revelle (2015)) ")
  cat(round(x$glb.algebraic, DIGITS))
  cat("\nGLB.fa (greatest lower bounds by Ten Berge & Kiers (1991))        ")
  cat(round(x$glb.fa, DIGITS))
}